### ISSUE TITLE
Simple tutorial / guide needed

### ISSUE THREAD

**Issue by ghost** [theall/leveleditor#1]
Hey, I'm excited to see this project being developed and wanted to make some VS Levels for Multihero.

I downloaded the program and looks really cool. Much better than the native one that looks wierd and confusing. Still, I do need a simple guide for VS level making to get started, so please add one in the help menu of the program.

**Comment by theall** [comment]
I don't think it's a good time to try this editor.It's still in developing, many features are not done yet,however we keeps working on it.We plan to publish this tool in 6 months.

**Comment by ghost** [comment]
Oh its still that early in development, I did not realize this. I thought the tool was already functional, but just lacked a guide and some bug fixes.

Probably best I close this issue and wait for 6 months, does not make sense to leave it open right now.

Thank you for the answer btw. : )

**Comment by zeto0128** [comment]
Nice to see you guys still around. I have decided to come back from hiatus and continue with the character creation. I also managed to find a way to convert the map resolution from 640 x 480 to 1024 x 768 in just a press of a certain button. This resolution will make the character sprites more detailed and better looking.

**Comment by theall** [comment]
> Nice to see you guys still around. I have decided to come back from hiatus and continue with the character creation. I also managed to find a way to convert the map resolution from 640 x 480 to 1024 x 768 in just a press of a certain button. This resolution will make the character sprites more detailed and better looking.

Great job
